### ISSUE TITLE
Melodic-devel to build husky from scratch

### ISSUE THREAD

**Issue by dolikemedo** [husky/husky_robot#21]
Hi! Can I use this to build husky workspace from scratch? Why no melodic version? Thanks!

**Comment by tonybaltovski** [comment]
Use this for Melodic source build: https://github.com/husky/husky/tree/melodic-devel

**Comment by dolikemedo** [comment]
Thanks!
I tried it, and I finally got it to compile, but I cant seem to figure how to launch. 
Is there any official launch files? Husky bringup fails. 
I'm trying to do this in docker, because I built a custom AMR before, and everything was in docker.
Control, Odom, movebase etc.
anyways, Thanks!
