### ISSUE TITLE
UM7 IMU

### ISSUE THREAD

**Issue by SOHAILMBS** [husky/husky_robot#26]
**PC information:**
 - OS:  Ubuntu 20.04
 - ROS Distro:  Noetic
 - Built from source:
 - Package version: ros-noetic-husky-robot

 **Expected behaviour**
UM7 IMU calibration file.

 **Actual behaviour**
No calibrationfile.

Solution is already available in your ridgeback repo for fixing. It was just changing the python compute_calibration line 42 with:

`vecs.append((float(msg.magnetic_field.x), float(msg.magnetic_field.y), float(msg.magnetic_field.z)))`

Now works well.

**To Reproduce**
Running the UM7 IMU calibration.

**Comment by tonybaltovski** [comment]
Thanks for reporting this!  It was fixed in [5db998f](https://github.com/husky/husky_robot/commit/5db998f6478998279d5e2a2f89aac5884aae7dd7).
