### ISSUE TITLE
Change to UR modern driver

### ISSUE THREAD

**Issue by ibaranov-cp** [husky/husky_robot#8]
Old driver is depercated and broken

Please change:
https://github.com/husky/husky_robot/blob/indigo-devel/husky_bringup/launch/ur5_arm_config/ur5.launch#L47

To
  <node name="ur_driver" pkg="ur_modern_driver" type="ur_driver" output="screen">

And ensure that ur_modern driver is installed and depended on, rather than ur_driver!

**Comment by UltronDestroyer** [comment]
@paulbovbel I believe @tonybaltovski  is maintainer now

Sorry, realized this is UR. I'll take a look

**Comment by UltronDestroyer** [comment]
Solved with https://github.com/husky/husky_robot/commit/bd061e0a69d390c66530070f7526554afc2c5491
